### ISSUE TITLE
What's the difference between vrc and vrc_plus?

### ISSUE THREAD

**Issue by XMU-qcj** [wutong16/Density_aware_Chamfer_Distance#6]

**Comment by wutong16** [comment]
Hi @Unknownnnnnnn ,

vrc is the framework that was proposed along with the MVP dataset used in this paper, viewed as one of our baselines; 
vrc_plus contains our technical contributions to the training pipeline and architecture proposed by our paper. It is named vrc_plus since our new modules are incorporated with the original vrc model.
